apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-certs
  namespace: knative-serving
  labels:
    serving-certs-ctrl: "data-plane"
    networking.internal.knative.dev/certificate-uid: "serving-certs"
# The data is populated when internal-encryption is enabled.